version: '3.8'

services:
  ado-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_DEVOPS_PAT=${AZURE_DEVOPS_PAT}
      - AZURE_DEVOPS_PROJECT=${AZURE_DEVOPS_PROJECT}
      - AZURE_DEVOPS_ORGANIZATION_URL=${AZURE_DEVOPS_ORGANIZATION_URL}
      - MCP_SERVER_PORT=8000
    volumes:
      # Mount .env file for local development
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
